  
## see https://travis-ci.org/phillip-kruger/apiee
language: java

## export GPG details
before_install:
##      - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key -in all.gpg.enc -out all.gpg -d
##      - gpg --import all.gpg
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  
install:
    ##mvn --settings .maven.xml install -Dgpg.skip
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

## Build and release to maven central  
script: 
    mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease

## Get the project version
before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    
cache:
    directories:
        - ~/.m2/repository
